spring.application.name=examruntime-service
server.port=8084
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
spring.web.error.include-message=always

spring.datasource.url=${DB_EXAM_URL}
spring.datasource.username=${DB_EXAM_USERNAME}
spring.datasource.password=${DB_EXAM_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

services.auth.base-url=${AUTH_SERVICE_URL}
services.question.base-url=${QUESTION_SERVICE_URL}
services.internal-api-key=${INTERNAL_API_KEY}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}