spring.application.name=exam-service
server.port=8083
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
spring.web.error.include-message=always

spring.datasource.url=${DB_EXAM_URL:jdbc:postgresql://localhost:5435/exam-service-db}
spring.datasource.username=${DB_EXAM_USERNAME:postgres}
spring.datasource.password=${DB_EXAM_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

services.auth.base-url=${AUTH_SERVICE_URL:http://localhost:8081}
services.question.base-url=${QUESTION_SERVICE_URL:http://localhost:8082}
services.internal-api-key=${INTERNAL_API_KEY:local-internal-key}
